// ─── Template Loader ──────────────────────────────────────────────────────────
//
// Loads pre-defined ReactFlow-compatible schema skeletons for detected templates.
// Multi-template: merges nodes + edges from all matched templates, deduplicating.
// ─────────────────────────────────────────────────────────────────────────────

import type { TemplateName } from "./templateDetector";
import type { SchemaNode, SchemaEdge } from "../ai/types";

interface TemplateSchema {
  nodes: SchemaNode[];
  edges: SchemaEdge[];
}

// ─── Template definitions ──────────────────────────────────────────────────────

const TEMPLATES: Record<TemplateName, TemplateSchema> = {
  ecommerce: {
    nodes: [
      {
        id: "users",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "users",
          columns: [
            {
              id: "users_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_email",
              name: "email",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "users_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "products",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "products",
          columns: [
            {
              id: "products_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "products_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "products_price",
              name: "price",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "products_stock",
              name: "stock_quantity",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "0",
            },
            {
              id: "products_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "orders",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "orders",
          columns: [
            {
              id: "orders_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "orders_user_id",
              name: "user_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "orders_status",
              name: "status",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "'pending'",
            },
            {
              id: "orders_total",
              name: "total_amount",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "orders_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "order_items",
        type: "tableNode",
        position: { x: 700, y: 400 },
        data: {
          label: "order_items",
          columns: [
            {
              id: "oi_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "oi_order_id",
              name: "order_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "oi_product_id",
              name: "product_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "oi_quantity",
              name: "quantity",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "oi_unit_price",
              name: "unit_price",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
          ],
        },
      },
      {
        id: "payments",
        type: "tableNode",
        position: { x: 1050, y: 0 },
        data: {
          label: "payments",
          columns: [
            {
              id: "pay_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "pay_order_id",
              name: "order_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "pay_amount",
              name: "amount",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "pay_method",
              name: "payment_method",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "pay_status",
              name: "status",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "pay_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "categories",
        type: "tableNode",
        position: { x: 350, y: 400 },
        data: {
          label: "categories",
          columns: [
            {
              id: "cat_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "cat_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "cat_slug",
              name: "slug",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_orders_users",
        source: "orders",
        target: "users",
        sourceHandle: "orders_user_id",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "many-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_oi_orders",
        source: "order_items",
        target: "orders",
        sourceHandle: "oi_order_id",
        targetHandle: "orders_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_oi_products",
        source: "order_items",
        target: "products",
        sourceHandle: "oi_product_id",
        targetHandle: "products_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "RESTRICT" },
      },
      {
        id: "e_pay_orders",
        source: "payments",
        target: "orders",
        sourceHandle: "pay_order_id",
        targetHandle: "orders_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
    ],
  },

  blog: {
    nodes: [
      {
        id: "users",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "users",
          columns: [
            {
              id: "users_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_username",
              name: "username",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_email",
              name: "email",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "posts",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "posts",
          columns: [
            {
              id: "posts_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "posts_author_id",
              name: "author_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "posts_title",
              name: "title",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "posts_body",
              name: "body",
              type: "TEXT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "posts_slug",
              name: "slug",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "posts_published",
              name: "published_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
            {
              id: "posts_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "comments",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "comments",
          columns: [
            {
              id: "cmt_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "cmt_post_id",
              name: "post_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "cmt_user_id",
              name: "user_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "cmt_body",
              name: "body",
              type: "TEXT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "cmt_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "tags",
        type: "tableNode",
        position: { x: 350, y: 400 },
        data: {
          label: "tags",
          columns: [
            {
              id: "tag_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "tag_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "tag_slug",
              name: "slug",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_posts_users",
        source: "posts",
        target: "users",
        sourceHandle: "posts_author_id",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_cmt_posts",
        source: "comments",
        target: "posts",
        sourceHandle: "cmt_post_id",
        targetHandle: "posts_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_cmt_users",
        source: "comments",
        target: "users",
        sourceHandle: "cmt_user_id",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
    ],
  },

  saas: {
    nodes: [
      {
        id: "organizations",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "organizations",
          columns: [
            {
              id: "org_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "org_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "org_slug",
              name: "slug",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "org_plan",
              name: "plan",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "'free'",
            },
            {
              id: "org_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "users",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "users",
          columns: [
            {
              id: "users_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_org_id",
              name: "organization_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "users_email",
              name: "email",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_role",
              name: "role",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "'member'",
            },
            {
              id: "users_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "subscriptions",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "subscriptions",
          columns: [
            {
              id: "sub_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "sub_org_id",
              name: "organization_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sub_plan",
              name: "plan",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sub_status",
              name: "status",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sub_start",
              name: "started_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sub_end",
              name: "ends_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_users_orgs",
        source: "users",
        target: "organizations",
        sourceHandle: "users_org_id",
        targetHandle: "org_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_sub_orgs",
        source: "subscriptions",
        target: "organizations",
        sourceHandle: "sub_org_id",
        targetHandle: "org_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
    ],
  },

  restaurant: {
    nodes: [
      {
        id: "menus",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "menus",
          columns: [
            {
              id: "menu_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "menu_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "menu_active",
              name: "is_active",
              type: "BOOLEAN",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "true",
            },
          ],
        },
      },
      {
        id: "menu_items",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "menu_items",
          columns: [
            {
              id: "mi_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "mi_menu_id",
              name: "menu_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "mi_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "mi_price",
              name: "price",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "mi_available",
              name: "is_available",
              type: "BOOLEAN",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "true",
            },
          ],
        },
      },
      {
        id: "orders",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "orders",
          columns: [
            {
              id: "orders_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "orders_table",
              name: "table_number",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
            {
              id: "orders_status",
              name: "status",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "'open'",
            },
            {
              id: "orders_total",
              name: "total",
              type: "DECIMAL",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "orders_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "order_lines",
        type: "tableNode",
        position: { x: 700, y: 400 },
        data: {
          label: "order_lines",
          columns: [
            {
              id: "ol_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "ol_order_id",
              name: "order_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "ol_item_id",
              name: "menu_item_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "ol_qty",
              name: "quantity",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_mi_menu",
        source: "menu_items",
        target: "menus",
        sourceHandle: "mi_menu_id",
        targetHandle: "menu_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_ol_orders",
        source: "order_lines",
        target: "orders",
        sourceHandle: "ol_order_id",
        targetHandle: "orders_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_ol_items",
        source: "order_lines",
        target: "menu_items",
        sourceHandle: "ol_item_id",
        targetHandle: "mi_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "RESTRICT" },
      },
    ],
  },

  inventory: {
    nodes: [
      {
        id: "products",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "products",
          columns: [
            {
              id: "prod_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "prod_sku",
              name: "sku",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "prod_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "prod_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "warehouses",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "warehouses",
          columns: [
            {
              id: "wh_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "wh_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "wh_location",
              name: "location",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
          ],
        },
      },
      {
        id: "stock_levels",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "stock_levels",
          columns: [
            {
              id: "sl_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "sl_product_id",
              name: "product_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sl_warehouse_id",
              name: "warehouse_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sl_qty",
              name: "quantity",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "0",
            },
            {
              id: "sl_reorder",
              name: "reorder_point",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "10",
            },
          ],
        },
      },
      {
        id: "suppliers",
        type: "tableNode",
        position: { x: 0, y: 400 },
        data: {
          label: "suppliers",
          columns: [
            {
              id: "sup_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "sup_name",
              name: "name",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "sup_contact",
              name: "contact_email",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_sl_prod",
        source: "stock_levels",
        target: "products",
        sourceHandle: "sl_product_id",
        targetHandle: "prod_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_sl_wh",
        source: "stock_levels",
        target: "warehouses",
        sourceHandle: "sl_warehouse_id",
        targetHandle: "wh_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
    ],
  },

  social_network: {
    nodes: [
      {
        id: "users",
        type: "tableNode",
        position: { x: 0, y: 0 },
        data: {
          label: "users",
          columns: [
            {
              id: "users_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_username",
              name: "username",
              type: "VARCHAR",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "users_bio",
              name: "bio",
              type: "TEXT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: true,
              isUnique: false,
            },
            {
              id: "users_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "posts",
        type: "tableNode",
        position: { x: 350, y: 0 },
        data: {
          label: "posts",
          columns: [
            {
              id: "posts_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "posts_user_id",
              name: "user_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "posts_body",
              name: "body",
              type: "TEXT",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "posts_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "follows",
        type: "tableNode",
        position: { x: 700, y: 0 },
        data: {
          label: "follows",
          columns: [
            {
              id: "fol_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "fol_follower",
              name: "follower_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "fol_following",
              name: "following_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "fol_created_at",
              name: "created_at",
              type: "TIMESTAMP",
              isPrimaryKey: false,
              isForeignKey: false,
              isNullable: false,
              isUnique: false,
              defaultValue: "NOW()",
            },
          ],
        },
      },
      {
        id: "likes",
        type: "tableNode",
        position: { x: 700, y: 400 },
        data: {
          label: "likes",
          columns: [
            {
              id: "like_id",
              name: "id",
              type: "SERIAL",
              isPrimaryKey: true,
              isForeignKey: false,
              isNullable: false,
              isUnique: true,
            },
            {
              id: "like_post_id",
              name: "post_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
            {
              id: "like_user_id",
              name: "user_id",
              type: "INT",
              isPrimaryKey: false,
              isForeignKey: true,
              isNullable: false,
              isUnique: false,
            },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e_posts_users",
        source: "posts",
        target: "users",
        sourceHandle: "posts_user_id",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_fol_follower",
        source: "follows",
        target: "users",
        sourceHandle: "fol_follower",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_fol_following",
        source: "follows",
        target: "users",
        sourceHandle: "fol_following",
        targetHandle: "users_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
      {
        id: "e_like_posts",
        source: "likes",
        target: "posts",
        sourceHandle: "like_post_id",
        targetHandle: "posts_id",
        type: "relationshipEdge",
        data: { relationshipType: "one-to-many", onDelete: "CASCADE" },
      },
    ],
  },
};

// ─── Multi-template merge ──────────────────────────────────────────────────────

/**
 * Load and merge schemas for all matched templates.
 * Deduplicates nodes (by ID) and edges (by ID).
 */
export function loadTemplate(templateNames: TemplateName[]): {
  nodes: SchemaNode[];
  edges: SchemaEdge[];
} {
  const nodeMap = new Map<string, SchemaNode>();
  const edgeMap = new Map<string, SchemaEdge>();
  let xOffset = 0;

  for (const name of templateNames) {
    const tmpl = TEMPLATES[name];
    if (!tmpl) continue;

    // Offset positions for multi-template merging
    for (const node of tmpl.nodes) {
      if (!nodeMap.has(node.id)) {
        nodeMap.set(node.id, {
          ...node,
          position: { x: node.position.x + xOffset, y: node.position.y },
        });
      }
    }

    for (const edge of tmpl.edges) {
      if (!edgeMap.has(edge.id)) {
        edgeMap.set(edge.id, edge);
      }
    }

    xOffset += 1400; // space out templates horizontally
  }

  return {
    nodes: Array.from(nodeMap.values()),
    edges: Array.from(edgeMap.values()),
  };
}
